### ISSUE TITLE
ITU-T A.1500 (T-Editing Guidelines): differences between generated DOC and PDF (continued from #60)

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-native-pdf#144]
- Title doesn't render well in PDF (apostrophe ' is rendered badly).

PDF:
![image](https://user-images.githubusercontent.com/55683568/80309572-2c0caa00-87d6-11ea-880f-c5922ba9fae9.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/80309580-362ea880-87d6-11ea-8da3-d3abd2154568.png)

- Abbreviations and acronyms subsection in section 8 is not numbered properly in PDF.

PDF:
![image](https://user-images.githubusercontent.com/55683568/80309644-9faeb700-87d6-11ea-91de-ea2bbbdae78a.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/80309654-ac330f80-87d6-11ea-81a5-0c3c804df622.png)

- Scope is rendered badly in PDF and it includes an additional subsection. (As I can see, note at the beginning of the section was added in .adoc because original document includes a footnote in document identifier, i.e. in header of the document, so I believe this part is fine).

PDF:
![image](https://user-images.githubusercontent.com/55683568/80309726-0fbd3d00-87d7-11ea-9649-7e710e013b11.png)
![image](https://user-images.githubusercontent.com/55683568/80309822-9114cf80-87d7-11ea-97c2-fe04f4015294.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/80309746-219ee000-87d7-11ea-81f4-31839c25d21b.png)
![image](https://user-images.githubusercontent.com/55683568/80309829-9a9e3780-87d7-11ea-8b6e-fbf1b5a16112.png)

- Small bracket after the footnote is not inserted in PDF, unlike in generated and original DOCs. Since some ITU documents include brackets after the footnotes in table entries, and some not, @ronaldtse could you please let us know did ITU provide some rule which should be applied in this case?

PDF:
![image](https://user-images.githubusercontent.com/55683568/80309891-14cebc00-87d8-11ea-8a64-c612da12b78e.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/80309913-30d25d80-87d8-11ea-9780-64567cd835d7.png)

- Notes are numbered differently in PDF and DOC (DOC restarts numbering per subsection, unlike PDF). I'm not sure whether this is a consequence of the wrong section number in PDF in this case.

PDF:
![image](https://user-images.githubusercontent.com/55683568/80310055-f5845e80-87d8-11ea-93f9-0067e5021db0.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/80310032-de457100-87d8-11ea-8732-f642c567234a.png)

- Different font size is used in table in this case:

DOC:
![image](https://user-images.githubusercontent.com/55683568/80310154-86f3d080-87d9-11ea-8e16-c7b2797beb81.png)

PDF:
![image](https://user-images.githubusercontent.com/55683568/80310158-8f4c0b80-87d9-11ea-8fa2-2f1ec669806f.png)

- Bibliography style differs. PDF includes more square brackets and "b-"s.

DOC:
![image](https://user-images.githubusercontent.com/55683568/80310209-d1754d00-87d9-11ea-914c-47a74cbda3a8.png)

PDF:
![image](https://user-images.githubusercontent.com/55683568/80310263-0e414400-87da-11ea-9164-64a70a93563d.png)

**Comment by Intelligent2013** [comment]
> Title doesn't render well in PDF (apostrophe ' is rendered badly).

The issue in source XML:
```
<title language="en" format="text/plain" type="main">Author&amp;#8217;s guide for drafting ITU-T Recommendations</title>
```

Should be:
```
<title language="en" format="text/plain" type="main">Author&#8217;s guide for drafting ITU-T Recommendations</title>
```

> Abbreviations and acronyms subsection in section 8 is not numbered properly in PDF.

Fixed.

> Scope is rendered badly in PDF and it includes an additional subsection. (As I can see, note at the beginning of the section was added in .adoc because original document includes a footnote in document identifier, i.e. in header of the document, so I believe this part is fine).

Additional subsection is a part of XML:
```
<clause id="Scope" obligation="normative">
	<title>Scope</title><p id="_896dca22-8745-4bf0-9b48-21309e4708a6">This Recommendation defines the following terms:</p>
	<terms obligation="normative">
		<title>Definitions</title><p id="_cd0ed414-df2a-4580-87f2-34d77adfd233">None.</p>
	</terms>
	<note id="_d60b467c-cc57-42ca-b89b-e26f4730c638">
		<p id="_e9b3613b-0178-4e0a-8054-1cbffc89eb84">Recommendation ITU-T A.1500 is a fictitious Recommendation. It was established for illustrative purposes only and constitutes an example of the proposed presentation style.</p>
	</note>...
```

> Notes are numbered differently in PDF and DOC (DOC restarts numbering per subsection, unlike PDF). I'm not sure whether this is a consequence of the wrong section number in PDF in this case.

Fixed.


> Different font size is used in table in this case:

Fixed.

> Bibliography style differs. PDF includes more square brackets and "b-"s.

Fixed.


Updated PDF here: https://github.com/metanorma/mn-native-pdf/blob/gh-pages/documents/itu-T-Editing-Guidelines-201602.pdf

**Comment by anermina** [comment]
I can confirm these fixes. @Intelligent2013 , could you please let me know who could help with the XML issues?

**Comment by Intelligent2013** [comment]
> I can confirm these fixes. @Intelligent2013 , could you please let me know who could help with the XML issues?

@opoudjis

**Comment by opoudjis** [comment]
@anermina (and for that matter @manuel489), I think you already know this, but the division of labour is:

I generate the XML from AsciiDoc
I generate the HTML and DOC from the XML
Alex D generates the PDF
We are working separately from each other
(Which means that I am not actively monitoring tickets assigned to Alex D, and issues  in my domain need to be brought up to me in separate tickets.)

**Comment by anermina** [comment]
> (Which means that I am not actively monitoring tickets assigned to Alex D, and issues in my domain need to be brought up to me in separate tickets.)

Sure @opoudjis , separate tickets were opened, but they just weren't assigned due to the other (higher priority) tasks. I will check if there is anything else that should be reported.

**Comment by anermina** [comment]
Remaining PDF issues:

- Cross-references to external sources are written in smaller font size than usual.

PDF:
![image](https://user-images.githubusercontent.com/55683568/81430095-2791ab00-915f-11ea-8995-8d7ae206cc37.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/81430122-35473080-915f-11ea-975d-0bc0db65ed58.png)

- Spacing between footnote descriptions (in tables) is bigger in PDF than in original document.

PDF:
![image](https://user-images.githubusercontent.com/55683568/81431252-25c8e700-9161-11ea-8f20-8fc5fef6a72e.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/81431269-2e212200-9161-11ea-8277-163aa81ef338.png)

**Comment by Intelligent2013** [comment]
> Cross-references to external sources are written in smaller font size than usual.

Fixed.

> Spacing between footnote descriptions (in tables) is bigger in PDF than in original document.

Fixed.

**Comment by anermina** [comment]
Thanks @Intelligent2013!

One more question regarding definition lists: It seems the width of the first column is bigger when the content is shorter, which makes the output a bit unexpected. Should this be happening according to the code?

PDF: 
![image](https://user-images.githubusercontent.com/55683568/82608962-e3b98f80-9bbb-11ea-929b-af9b013acbcc.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/82609303-8d008580-9bbc-11ea-898c-9f05fff0c5c5.png)

**Comment by Intelligent2013** [comment]
@anermina 
> It seems the width of the first column is bigger when the content is shorter, which makes the output a bit unexpected. 

I'll try to describe how it works in XSL-FO with Apache FOP processor.

In source xml there are few definition lists:

```
<dl id="_fc31251e-0490-4eab-8832-c7d0d2238be4">
<dt>[ITU-T G Suppl. 41]</dt>
<dd>
<p id="_7314ceae-7ec8-48cc-9737-8fc39c25f76b">ITU-T G-series Recommendations – Supplement 41 (2010), <em>Design guidelines for optical fibre submarine cable systems</em>.<br/></p>
</dd>
</dl>
```
```
<dl id="_2f6b7593-6979-4dec-8c12-165d990dd994">
<dt>[b-Trischitta]</dt>
<dd>
<p id="_2ca78144-71c9-461e-aa2d-58029cfa0cda">Trischitta, P.R., and Varma, E.L. (1989), <em>Jitter in Digital Transmission Systems</em>, Norwood, MA, Artech House.<br/></p>
</dd>
</dl>
```
```
<dl id="_4fee27d1-baa4-4542-bbdf-2f45407c6c52">
<dt>[b-Cornaglia]</dt>
<dd>
<p id="_b36fef5d-1b71-4955-acc3-63af3d7f81ff">Cornaglia, B., Pane, P., and Spini, M. (1995), <em>Errored Block Detection with Bit Interleaved Parity Failures in SDH Network</em>, IEEE Transactions on Communications, Vol. 43, No. 12, December, pp. 2904-2906.<br/></p>
</dd>
</dl>
```
```
<dl id="_1f5ea213-fc98-488b-b29e-e929e96c718f">
<dt>[b-W3C HTML 4.01]</dt>
<dd>
<p id="_9a40ec1f-ed87-4ce8-ac06-4db04927f38c"><em>W3C, HTML 4.01 Specification</em>, W3C Recommendation 24 December 1999.<br/>
<link target="http://www.w3.org/TR/1999/REC-html401-19991224/"/></p>
</dd>
</dl>
```

To display `dl` via XSL-FO I use `table` structure. Apache FOP (FO Processor) doesn't support auto table-layout feature (`The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table)`). Therefore in XSL I calculate proportional table width for each column depends on longest word in table cell.  For example, for 1st definition list:
```
<dl id="_fc31251e-0490-4eab-8832-c7d0d2238be4">
<dt>[ITU-T G Suppl. 41]</dt>
<dd>
<p id="_7314ceae-7ec8-48cc-9737-8fc39c25f76b">ITU-T G-series Recommendations – Supplement 41 (2010), <em>Design guidelines for optical fibre submarine cable systems</em>.<br/></p>
</dd>
</dl>
```

in `dt` (left column) we have a text: `[ITU-T G Suppl. 41]`, which contains "words":
- [ITU-T
- G 
- Suppl.
- 41
The longest word is: `Suppl.` (6 characters)

in `dd` (right column) there are text: `ITU-T G-series Recommendations – Supplement 41 (2010), Design guidelines for optical fibre submarine cable systems`, which contains "words":
- ITU-T
- G-series
- Recommendations
- Supplement 
- ...

The longest word is: `Recommendations` (15 characters).
Therefore in XSL-FO we get for 1st definition list:
```
column-width="proportional-column-width(6)"
column-width="proportional-column-width(15)"
```
It means, that table has width 21 'units', i.e. left column 'uses' 6 units, right column - 15 units. Or, in other words, right column has width x2.5 width than left column.

I can't to think up another algorithm to better visualization.

**Comment by anermina** [comment]
Thank you for the explanation, @Intelligent2013 ! I don't have a better idea which wouldn't be too complicated...

Can you please check this remaining issue:
- Duplicated brackets are still present in PDF, although this issue is solved in DOC.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83913774-41c7a480-a770-11ea-9e08-10ca492bbfdb.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83913821-56a43800-a770-11ea-89dd-6bbf5ad6cb9b.png)

As far as I'm concerned, this ticket can be closed after you check this, since all the document-specific issues are reported and checked. Remaining general issues will be reported in a separate ticket.

**Comment by Intelligent2013** [comment]
> Duplicated brackets are still present in PDF, although this issue is solved in DOC.

Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/83968365-64250380-a8d1-11ea-9a35-42dd4972bbb6.png)
